sonar.projectKey=Les-Chauffagistes_hash-contenders-referee
sonar.projectName=Hash Contenders Referee

sonar.sources=src,main.py,state.py,init.py
sonar.tests=tests
sonar.python.version=3

sonar.python.coverage.reportPaths=coverage.xml

sonar.cpd.exclusions=tests/**