name: test-docker
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: [self-hosted, macOS]

    steps:
        - name: Check Docker
          run: |
            which docker || true
            docker --version || true
            docker info || true